import 'package:flutter/material.dart';

class RadioStation {
  final String id;
  final String name;
  final String streamUrl;
  final String frequency;
  final Color primaryColor;
  final Color secondaryColor;
  final String description;
  final String? logoUrl;
  final String? logoAsset;

  const RadioStation({
    required this.id,
    required this.name,
    required this.streamUrl,
    required this.frequency,
    required this.primaryColor,
    required this.secondaryColor,
    required this.description,
    this.logoUrl,
    this.logoAsset,
  });

  static const List<RadioStation> stations = [
    RadioStation(
      id: 'hiru_fm',
      name: 'Hiru FM',
      streamUrl: 'https://radio.lotustechnologieslk.net:2020/stream/hirufmgarden',
      frequency: '96.1 MHz',
      primaryColor: Color(0xFFD32F2F),
      secondaryColor: Color(0xFFFF5722),
      description: 'Sri Lanka\'s Number One Sinhala Radio Channel',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/8/7868.v14.png',
      logoAsset: 'assets/logos/hiru fm.jpg',
    ),
    RadioStation(
      id: 'fm_derana',
      name: 'FM Derana',
      streamUrl: 'https://cp12.serverse.com/proxy/fmderana/stream',
      frequency: '92.2 MHz',
      primaryColor: Color(0xFFFF8F00),
      secondaryColor: Color(0xFFFFC107),
      description: 'Lankeya Sith Neth Niwana Derana',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/0/7860.v12.png',
      logoAsset: 'assets/logos/fm derana.jpg',
    ),
    RadioStation(
      id: 'neth_fm',
      name: 'Neth FM',
      streamUrl: 'https://cp11.serverse.com/proxy/nethfm/stream',
      frequency: '98.9 MHz',
      primaryColor: Color(0xFF0D47A1),
      secondaryColor: Color(0xFF1976D2),
      description: 'The Radio for All Sri Lankans',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/1/7861.v10.png',
      logoAsset: 'assets/logos/neth fm.jpg',
    ),
    RadioStation(
      id: 'siyatha_fm',
      name: 'Siyatha FM',
      streamUrl: 'https://srv01.onlineradio.voaplus.com/siyathafm',
      frequency: '98.2 MHz',
      primaryColor: Color(0xFF6A1B9A),
      secondaryColor: Color(0xFFAB47BC),
      description: 'Vibrant Music and Hits All Day Long',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/2/7862.v12.png',
      logoAsset: 'assets/logos/siyatha fm.png',
    ),
    RadioStation(
      id: 'lakhanda_fm',
      name: 'Lakhanda FM',
      streamUrl: 'https://cp12.serverse.com/proxy/itnfm?mp=/stream',
      frequency: '93.7 MHz',
      primaryColor: Color(0xFF2E7D32),
      secondaryColor: Color(0xFF4CAF50),
      description: 'The Golden Heartbeat of the Nation',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/7/7867.v7.png',
      logoAsset: 'assets/logos/lakhanda.jpg',
    ),
    RadioStation(
      id: 'gold_fm',
      name: 'Gold FM',
      streamUrl: 'https://radio.lotustechnologieslk.net:8000/',
      frequency: '93.0 MHz',
      primaryColor: Color(0xFFFFD700),
      secondaryColor: Color(0xFF8B6508),
      description: 'Sri Lanka\'s Golden Classics English Station',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/9/7869.v15.png',
      logoAsset: 'assets/logos/gold fm.jpg',
    ),
    RadioStation(
      id: 'kiss_fm',
      name: 'Kiss FM',
      streamUrl: 'https://srv01.onlineradio.voaplus.com/kissfm',
      frequency: '96.9 MHz',
      primaryColor: Color(0xFFE91E63),
      secondaryColor: Color(0xFF1A1A1A),
      description: 'The Sound of Your Future',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/5/7875.v13.png',
      logoAsset: 'assets/logos/kiss fm.jpg',
    ),
    RadioStation(
      id: 'light_fm',
      name: 'Light FM',
      streamUrl: 'https://srv01.onlineradio.voaplus.com/lite878',
      frequency: '87.8 MHz',
      primaryColor: Color(0xFF00BFFF),
      secondaryColor: Color(0xFF1E3C72),
      description: 'Lite 87 - Easy Listening Favorites',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/4/7874.v14.png',
      logoAsset: 'assets/logos/light fm.png',
    ),
    RadioStation(
      id: 'real_radio',
      name: 'Real Radio',
      streamUrl: 'https://srv01.onlineradio.voaplus.com/realfm',
      frequency: '97.1 MHz',
      primaryColor: Color(0xFF008080),
      secondaryColor: Color(0xFF0F2027),
      description: 'Real Radio - real music, real talk',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/8/8048.v11.png',
      logoAsset: 'assets/logos/real radio.jpg',
    ),
    RadioStation(
      id: 'rhythm_fm',
      name: 'Rhythm FM',
      streamUrl: 'https://srv01.onlineradio.voaplus.com/rhythmfm',
      frequency: '95.6 MHz',
      primaryColor: Color(0xFFF27121),
      secondaryColor: Color(0xFFE94057),
      description: 'Feel the Rhythm of Your Life',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/9/7919.v10.png',
      logoAsset: 'assets/logos/rhythm fm.jpg',
    ),
    RadioStation(
      id: 'shaa_fm',
      name: 'Shaa FM',
      streamUrl: 'https://listen.radioking.com/radio/384487/stream/435781',
      frequency: '91.1 MHz',
      primaryColor: Color(0xFFFF2525),
      secondaryColor: Color(0xFFFF8F00),
      description: 'Sri Lanka\'s Youth Trend Broadcast',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/3/7873.v14.png',
      logoAsset: 'assets/logos/shaa fm.jpg',
    ),
    RadioStation(
      id: 'sitha_fm',
      name: 'Sitha FM',
      streamUrl: 'https://shaincast.caster.fm:48148/listen.mp3',
      frequency: '88.8 MHz',
      primaryColor: Color(0xFF7B1FA2),
      secondaryColor: Color(0xFF311B92),
      description: 'Sweet Sounds of Sinhala Broadcasting',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/2/8662.v4.png',
      logoAsset: 'assets/logos/sitha fm.jpg',
    ),
    RadioStation(
      id: 'sun_fm',
      name: 'Sun FM',
      streamUrl: 'https://radio.lotustechnologieslk.net:2020/stream/sunfmgarden',
      frequency: '98.9 MHz',
      primaryColor: Color(0xFFF12711),
      secondaryColor: Color(0xFFF5AF19),
      description: 'Sri Lanka\'s Ultimate English Hit Music Station',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/0/7870.v12.png',
      logoAsset: 'assets/logos/sun fm.png',
    ),
    RadioStation(
      id: 'v_fm',
      name: 'V FM',
      streamUrl: 'https://dc1.serverse.com/proxy/fmlanka/stream',
      frequency: '94.3 MHz',
      primaryColor: Color(0xFF00C9FF),
      secondaryColor: Color(0xFF92FE9D),
      description: 'V FM - The Voice of the People',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/5/7955.v11.png',
      logoAsset: 'assets/logos/v fm.jpg',
    ),
    RadioStation(
      id: 'yes_fm',
      name: 'Yes FM',
      streamUrl: 'http://live.trusl.com:1150/',
      frequency: '101.0 MHz',
      primaryColor: Color(0xFFE91E63),
      secondaryColor: Color(0xFF1E3C72),
      description: 'Sri Lanka\'s hit music and youth English radio station',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/6/7866.v14.png',
      logoAsset: 'assets/logos/yes fm.png',
    ),
    RadioStation(
      id: 'sirasa_fm',
      name: 'Sirasa FM',
      streamUrl: 'http://live.trusl.com:1170/;',
      frequency: '106.5 MHz',
      primaryColor: Color(0xFFE53935),
      secondaryColor: Color(0xFFFFD54F),
      description: 'Sri Lanka\'s popular Sinhala radio channel',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/4/7864.v14.png',
      logoAsset: 'assets/logos/sirasa fm.jpg',
    ),
    RadioStation(
      id: 'shakthi_fm',
      name: 'Shakthi FM',
      streamUrl: 'http://live.trusl.com:1160/;',
      frequency: '102.7 MHz',
      primaryColor: Color(0xFF1565C0),
      secondaryColor: Color(0xFFEF6C00),
      description: 'The premier Tamil radio station in Sri Lanka',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/3/7863.v14.png',
      logoAsset: 'assets/logos/shakthi fm.png',
    ),
    RadioStation(
      id: 'y_fm',
      name: 'Y FM',
      streamUrl: 'http://live.trusl.com:1180/;',
      frequency: '92.7 MHz',
      primaryColor: Color(0xFF8E24AA),
      secondaryColor: Color(0xFF00E5FF),
      description: 'Sri Lanka\'s trendsetting Sinhala youth station',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/5/7865.v14.png',
      logoAsset: 'assets/logos/y fm.png',
    ),
    RadioStation(
      id: 'tnl_radio',
      name: 'TNL Radio',
      streamUrl: 'http://live.tnlrn.com:8010/live.mp3',
      frequency: '101.8 MHz',
      primaryColor: Color(0xFF212121),
      secondaryColor: Color(0xFFB0BEC5),
      description: 'Sri Lanka\'s home of rock and alternative music',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/8/7878.v14.png',
      logoAsset: 'assets/logos/tnl radio.jpg',
    ),
    RadioStation(
      id: 'sooriyan_fm',
      name: 'Sooriyan FM',
      streamUrl: 'http://sooriyanfm.asiabroadcasting.stream:7071/;',
      frequency: '103.4 MHz',
      primaryColor: Color(0xFFE65100),
      secondaryColor: Color(0xFFFFD54F),
      description: 'Leading Tamil broadcasting network in Sri Lanka',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/0/7880.v12.png',
      logoAsset: 'assets/logos/sooriyan fm.jpg',
    ),
    RadioStation(
      id: 'varnam_fm',
      name: 'Varnam FM',
      streamUrl: 'http://s3.voscast.com:8402/',
      frequency: '90.4 MHz',
      primaryColor: Color(0xFF00E676),
      secondaryColor: Color(0xFF00B0FF),
      description: 'Sri Lanka\'s vibrant Tamil music station',
      logoUrl: 'https://cdn.onlineradiobox.com/img/logo/1/7881.v13.png',
      logoAsset: 'assets/logos/varnam fm.jpg',
    ),
  ];
}
